name: Scheduled Action Every Day

on:
  # Ejecuta automáticamente a medianoche UTC
  schedule:
    - cron: '0 0 * * *'
  
  # Permite ejecución manual desde la pestaña Actions
  workflow_dispatch:

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python main_script.py
