on:
  push:
    branches: [main]
  workflow_dispatch:  # permite correr manualmente
  schedule:
    # Ejecutar cada 5 minutos de 8:00 AM a 22:00 PM (hora Argentina)
    - cron: '*/5 8-21 * * *'


jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    env:  
      SECRET_BOT_TOKEN: ${{ secrets.SECRET_BOT_TOKEN }}  # tu token de Telegram como secreto  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Setup Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: 3.12  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper + Telegram script
        run: python main_script.py
