name: Playwright Scraper + Telegram

on:
  push:
    branches: [main]
  workflow_dispatch:  # permite correr manualmente
  schedule:
    # Corre cada 5 minutos entre las 8:00 y 22:00 (hora Argentina = UTC-3)
    # → En UTC: de 11:00 a 01:55 del día siguiente
    - cron: "*/5 11-23,0-1 * * *"

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    env:  
      SECRET_BOT_TOKEN: ${{ secrets.SECRET_BOT_TOKEN }}  # tu token de Telegram como secreto  

    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Setup Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: 3.12  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright asyncio psycopg2-binary requests pytz python-dotenv

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run scraper + Telegram script
        run: python main_script.py
